name: FOSDEM Event Desktop App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs

jobs:
  desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      TERM: dumb

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup

    - name: Build Desktop App
      run: ./gradlew jvmTest :desktop-app:packageDistributionForCurrentOS

    - name: Upload build outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: desktop-build-binaries-${{ matrix.os }}
        path: desktop-app/build/compose/binaries

    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: desktop-reports-${{ matrix.os }}
        path: |
          **/build/reports/*

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: desktop-test-results-${{ matrix.os }}
        path: |
          **/build/test-results/*
